import { useState, useEffect } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import Layout from "../../components/layout/Layout";
import { uploadEvidence } from "../../services/evidenceService";
import { getIncidents } from "../../services/incidentService";
import {
  Upload,
  ArrowLeft,
  HardDrive,
  Hash,
  Shield,
  Link as LinkIcon,
  AlertCircle,
  Loader2,
  RefreshCw,
} from "lucide-react";

export default function UploadEvidence() {
  const navigate = useNavigate();
  const { incidentId: routeIncidentId } = useParams();
  const [searchParams] = useSearchParams();

  const [incidentsList, setIncidentsList] = useState([]);
  const [loadingIncidents, setLoadingIncidents] = useState(true);

  const defaultIncident = routeIncidentId || searchParams.get("incidentId") || "";

  const [selectedIncidentId, setSelectedIncidentId] = useState(defaultIncident);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [evidenceType, setEvidenceType] = useState("log");
  const [status, setStatus] = useState("collected");
  const [selectedFile, setSelectedFile] = useState(null);

  const [uploading, setUploading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [serverError, setServerError] = useState("");

  const fetchIncidents = async () => {
    try {
      setLoadingIncidents(true);
      const res = await getIncidents({ limit: 100 });
      if (res.success && Array.isArray(res.incidents)) {
        setIncidentsList(res.incidents);
        if (!selectedIncidentId && res.incidents.length > 0) {
          setSelectedIncidentId(res.incidents[0]._id);
        }
      }
    } catch (err) {
      console.error("[UploadEvidence] Failed to fetch incidents:", err);
    } finally {
      setLoadingIncidents(false);
    }
  };

  useEffect(() => {
    fetchIncidents();
  }, []);

  useEffect(() => {
    if (routeIncidentId) {
      setSelectedIncidentId(routeIncidentId);
    }
  }, [routeIncidentId]);

  const parentIncident = incidentsList.find(
    (i) => i._id === selectedIncidentId || i.incidentId === selectedIncidentId
  );

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedFile(file);
      if (!name) {
        setName(file.name);
      }
    }
  };

  const handleUploadSubmit = async (e) => {
    e.preventDefault();
    if (!selectedFile) {
      setServerError("Please select a file to upload.");
      return;
    }
    if (!selectedIncidentId) {
      setServerError("Please select a parent incident case.");
      return;
    }

    try {
      setUploading(true);
      setProgress(0);
      setServerError("");

      const formData = new FormData();
      formData.append("file", selectedFile);
      formData.append("incidentId", selectedIncidentId);
      formData.append("name", name.trim() || selectedFile.name);
      formData.append("description", description.trim());
      formData.append("evidenceType", evidenceType);
      formData.append("status", status);

      const res = await uploadEvidence(formData, (percent) => {
        setProgress(percent);
      });

      if (res.success && res.evidence) {
        const targetId = res.evidence.evidenceId || res.evidence._id;
        navigate(`/evidence/${targetId}`);
      } else {
        setServerError(res.message || "Failed to ingest evidence artifact.");
      }
    } catch (err) {
      console.error("[UploadEvidence] API error:", err);
      setServerError(
        err.response?.data?.message || "Failed to upload evidence artifact. Access denied or invalid file type."
      );
    } finally {
      setUploading(false);
    }
  };

  return (
    <Layout>
      {/* Back Button & Header */}
      <div className="mb-6">
        <button
          onClick={() => (routeIncidentId ? navigate(`/incidents/${routeIncidentId}`) : navigate("/evidence"))}
          className="flex items-center gap-1.5 text-xs text-blue-400 hover:text-blue-300 font-medium mb-3 transition cursor-pointer"
        >
          <ArrowLeft size={14} /> Back to {routeIncidentId ? `Incident ${routeIncidentId}` : "All Evidence"}
        </button>
        <h1 className="text-2xl lg:text-3xl font-bold text-white tracking-tight flex items-center gap-3">
          <Upload className="text-blue-500" size={28} /> Upload Digital Evidence Artifact
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Attach digital forensic files to an active incident case. SHA-256 hash will be generated by backend.
        </p>
      </div>

      {/* Linked Route Parameter Banner */}
      {routeIncidentId && (
        <div className="mb-6 p-3.5 bg-blue-500/10 border border-blue-500/30 rounded-xl text-xs text-blue-300 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <LinkIcon size={16} className="text-blue-400" />
            <span>
              Pre-selected Parent Incident Case:{" "}
              <strong className="font-mono text-white">{routeIncidentId}</strong>
              {parentIncident ? ` — ${parentIncident.title}` : ""}
            </span>
          </div>
          <span className="text-[10px] bg-blue-500/20 px-2 py-0.5 rounded font-mono text-blue-200">
            Route Parameter Active
          </span>
        </div>
      )}

      {/* Server Error Alert */}
      {serverError && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 mb-6 flex items-center gap-3 text-red-400 text-xs max-w-5xl">
          <AlertCircle size={18} className="shrink-0" />
          <span>{serverError}</span>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 text-xs">
        {/* Upload Form (Left Column) */}
        <div className="lg:col-span-7 bg-[#0b1827] border border-[#203246] rounded-2xl p-6 shadow-2xl space-y-5">
          <form onSubmit={handleUploadSubmit} className="space-y-5">
            {/* Parent Incident Case */}
            <div>
              <label className="block text-slate-300 font-semibold mb-1.5 flex items-center justify-between">
                <span>Belongs to Parent Incident Case *</span>
                {routeIncidentId && (
                  <span className="text-[10px] text-emerald-400 font-mono">
                    Locked from route /incidents/{routeIncidentId}
                  </span>
                )}
              </label>
              {loadingIncidents ? (
                <div className="flex items-center gap-2 text-slate-400 py-2">
                  <Loader2 size={16} className="animate-spin text-blue-500" />
                  <span>Loading incident cases...</span>
                </div>
              ) : (
                <select
                  value={selectedIncidentId}
                  onChange={(e) => setSelectedIncidentId(e.target.value)}
                  className="w-full bg-[#071322] border border-[#1d334c] rounded-lg px-3.5 py-2.5 text-slate-200 outline-none cursor-pointer"
                >
                  <option value="">-- Select Parent Incident --</option>
                  {incidentsList.map((inc) => (
                    <option key={inc._id} value={inc._id}>
                      {inc.incidentId || inc._id}: {inc.title}
                    </option>
                  ))}
                </select>
              )}
            </div>

            <div>
              <label className="block text-slate-300 font-semibold mb-1.5">Evidence Title / Name</label>
              <input
                type="text"
                placeholder="e.g. Memory Dump - Server Auth WS-01"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full bg-[#071322] border border-[#1d334c] rounded-lg px-3.5 py-2.5 text-slate-200 outline-none focus:border-blue-500 transition"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-slate-300 font-semibold mb-1.5">Evidence Category Type *</label>
                <select
                  value={evidenceType}
                  onChange={(e) => setEvidenceType(e.target.value)}
                  className="w-full bg-[#071322] border border-[#1d334c] rounded-lg px-3.5 py-2.5 text-slate-200 outline-none cursor-pointer"
                >
                  <option value="log">Log File</option>
                  <option value="document">Document</option>
                  <option value="image">Image</option>
                  <option value="video">Video</option>
                  <option value="audio">Audio</option>
                  <option value="memory_dump">Memory Dump</option>
                  <option value="disk_image">Disk Image</option>
                  <option value="network_capture">Network Capture</option>
                  <option value="other">Other</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-300 font-semibold mb-1.5">Initial Status</label>
                <select
                  value={status}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-full bg-[#071322] border border-[#1d334c] rounded-lg px-3.5 py-2.5 text-slate-200 outline-none cursor-pointer"
                >
                  <option value="collected">Collected</option>
                  <option value="under_investigation">Under Investigation</option>
                  <option value="verified">Verified</option>
                  <option value="archived">Archived</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-slate-300 font-semibold mb-1.5">Description & Acquisition Notes</label>
              <textarea
                rows="3"
                placeholder="Contextual notes regarding artifact acquisition, physical location, or custodial notes..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full bg-[#071322] border border-[#1d334c] rounded-lg p-3 text-slate-200 outline-none focus:border-blue-500 transition leading-relaxed"
              />
            </div>

            {/* Dropzone File Input */}
            <div>
              <label className="block text-slate-300 font-semibold mb-1.5">File Selection / Dropzone *</label>
              <div className="border-2 border-dashed border-[#1e3856] hover:border-blue-500/60 rounded-xl p-6 text-center bg-[#071322] cursor-pointer transition">
                <input
                  type="file"
                  id="evidence-file-input"
                  onChange={handleFileChange}
                  className="hidden"
                />
                <label htmlFor="evidence-file-input" className="cursor-pointer flex flex-col items-center">
                  <HardDrive size={36} className="text-blue-400 mb-2" />
                  <span className="text-slate-200 font-semibold text-sm">
                    {selectedFile ? selectedFile.name : "Click to choose evidence file or drop file here"}
                  </span>
                  <span className="text-slate-500 text-[11px] mt-1">
                    {selectedFile
                      ? `${(selectedFile.size / 1024).toFixed(1)} KB`
                      : "Supports PCAP, Log, Memory Dumps, Binaries, Images, Documents (Executables blocked)"}
                  </span>
                </label>
              </div>
            </div>

            {/* Live Upload Progress Bar */}
            {uploading && (
              <div className="space-y-2 bg-[#071322] p-4 rounded-xl border border-blue-500/30">
                <div className="flex justify-between font-semibold text-blue-400 text-xs">
                  <span className="flex items-center gap-1.5">
                    <RefreshCw size={13} className="animate-spin" /> Uploading & Processing SHA-256 Hash...
                  </span>
                  <span>{progress}%</span>
                </div>
                <div className="w-full bg-[#050e18] h-2.5 rounded-full overflow-hidden border border-[#122336]">
                  <div
                    className="bg-blue-500 h-full transition-all duration-300 rounded-full"
                    style={{ width: `${progress}%` }}
                  />
                </div>
              </div>
            )}

            <div className="flex justify-end gap-3 pt-2">
              <button
                type="button"
                onClick={() => (routeIncidentId ? navigate(`/incidents/${routeIncidentId}`) : navigate("/evidence"))}
                className="px-4 py-2 bg-[#102236] hover:bg-[#172e48] text-slate-300 rounded-lg font-medium transition cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={!selectedFile || uploading}
                className="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white font-semibold rounded-lg shadow-lg shadow-blue-900/30 transition flex items-center gap-2 cursor-pointer"
              >
                {uploading ? (
                  <>
                    <Loader2 size={16} className="animate-spin" /> Uploading Evidence ({progress}%)...
                  </>
                ) : (
                  <>
                    <Upload size={16} /> Process & Ingest Evidence
                  </>
                )}
              </button>
            </div>
          </form>
        </div>

        {/* Info Right Column */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-[#0b1827] border border-[#203246] rounded-2xl p-5 shadow-2xl space-y-4">
            <h3 className="font-bold text-white text-sm border-b border-[#1b2d42] pb-3 flex items-center gap-2">
              <Shield size={16} className="text-blue-400" /> Parent Incident Context
            </h3>

            {parentIncident ? (
              <div className="bg-[#071322] border border-[#172a3e] p-3.5 rounded-xl space-y-1">
                <span className="font-mono text-blue-400 font-bold">{parentIncident.incidentId || parentIncident._id}</span>
                <strong className="block text-slate-200 text-xs">{parentIncident.title}</strong>
                <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">{parentIncident.description}</p>
              </div>
            ) : (
              <p className="text-slate-400 text-xs">Select an incident case to view summary context.</p>
            )}

            <div className="space-y-3 pt-2">
              <div className="p-3 bg-[#071322] border border-[#172a3e] rounded-xl space-y-1">
                <div className="flex items-center gap-2 text-slate-300 font-semibold">
                  <Hash size={15} className="text-amber-400" /> Streamed SHA-256 Hashing
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  The backend streams the uploaded file content and computes an authoritative SHA-256 hash stored in MongoDB.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
